FROM --platform=$TARGETOS/$TARGETARCH ghcr.io/pyrodactyl-oss/images:java_25

LABEL org.opencontainers.image.source="https://github.com/kotiacatone/hytale-docker"
LABEL org.opencontainers.image.licenses=MIT

USER root

RUN apt-get update -y \
    && apt-get install -y unzip jq curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/pterodactyl/yolks:java_25 /entrypoint.sh /java.sh
RUN chmod +x /java.sh

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

USER root
RUN chmod +x /entrypoint.sh
USER container

CMD [ "/bin/bash", "/entrypoint.sh" ]
