FROM --platform=$TARGETOS/$TARGETARCH ghcr.io/pterodactyl/yolks:java_25

LABEL author="kotiacatone" maintainer="https://github.com/kotiacatone"
LABEL org.opencontainers.image.source="https://github.com/kotiacatone/hytale-docker"

USER root

COPY --from=ghcr.io/pterodactyl/yolks:java_25 /entrypoint.sh /java.sh
RUN chmod +x /java.sh

RUN apt-get update -y \
    && apt-get install -y unzip jq curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ADD https://raw.githubusercontent.com/kotiacatone/hytale-docker/main/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

CMD [ "/bin/bash", "/entrypoint.sh" ]
